Repository prefix-dev/pixi, pull requests merged in 2025-01, with the labels that each got.

#2731 feat: move package fields under `[package]`.
  Cargo.lock
  crates/pixi_build_frontend/src/protocols/builders/pixi.rs
  crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs
  crates/pixi_build_frontend/src/protocols/mod.rs
  crates/pixi_build_frontend/tests/diagnostics.rs
  crates/pixi_build_types/Cargo.toml
  crates/pixi_build_types/src/procedures/initialize.rs
  crates/pixi_manifest/src/build_system.rs
  crates/pixi_manifest/src/error.rs
  crates/pixi_manifest/src/lib.rs
  crates/pixi_manifest/src/manifests/manifest.rs
  crates/pixi_manifest/src/manifests/package.rs
  crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__invalid_key@foobar.snap
  crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__invalid_key@hostdependencies.snap
  crates/pixi_manifest/src/preview.rs
  crates/pixi_manifest/src/toml/build_system.rs
  crates/pixi_manifest/src/toml/feature.rs
  crates/pixi_manifest/src/toml/manifest.rs
  crates/pixi_manifest/src/toml/mod.rs
  crates/pixi_manifest/src/toml/package.rs
  crates/pixi_manifest/src/toml/package_target.rs
  crates/pixi_manifest/src/toml/preview.rs
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__additional_build_backend_keys.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__additional_keys.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__disallow_source.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__empty_channels.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__missing_backend.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__missing_name.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__build_system__test__missing_version_specifier.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__build_dependencies_in_feature_with_pixi_build.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__host_dependencies_in_feature_with_pixi_build.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__missing_version.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__package_without_build_section.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__schema_must_be_string.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__target_workspace_dependencies.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__workspace_name_required.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__package__test__invalid_extra_key.snap
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__package__test__invalid_version.snap
  crates/pixi_manifest/src/toml/target.rs
  crates/pixi_manifest/src/toml/workspace.rs
  docs/build/backends.md
  docs/build/python.md
  docs/source_files/pixi_projects/pixi_build_cpp/pixi.toml
  docs/source_files/pixi_projects/pixi_build_python/pixi.toml
  docs/source_files/pixi_projects/pixi_build_workspace/packages/python_bindings/pixi.toml
  docs/source_files/pixi_projects/pixi_build_workspace/pixi.toml
  docs/source_files/pixi_tomls/dependency_types.toml
  docs/source_files/pixi_tomls/simple_pixi_build.toml
  examples/pixi-build/boltons/pixi.toml
  examples/pixi-build/cpp-sdl/pixi.toml
  schema/examples/valid/full.toml
  schema/model.py
  schema/schema.json
  tests/data/pixi_build/editable-pyproject/pyproject.toml
  tests/data/pixi_build/rattler-build-backend/pixi/pixi.toml
  tests/data/pixi_build/rich_example/pixi.toml
  tests/data/pixi_build/simple-pyproject/pyproject.toml
Labels: area:build

#2860 chore: bump rattler
  Cargo.lock
  Cargo.toml
  crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__table_name__tests__nameless_to_toml.snap
  crates/pixi_manifest/src/manifests/table_name.rs
  crates/pixi_manifest/src/pyproject.rs
  crates/pixi_spec/Cargo.toml
  crates/pixi_spec/src/snapshots/pixi_spec__toml__test__round_trip.snap
  crates/pixi_spec/src/toml.rs
  src/global/project/manifest.rs
  tests/integration_python/pixi_global/test_global.py
Labels: test:extra_slow

#2891 feat: add deprecation notice for `depends_on`
  crates/pixi_build_frontend/tests/diagnostics.rs
  crates/pixi_manifest/src/manifests/manifest.rs
  crates/pixi_manifest/src/pyproject.rs
  crates/pixi_manifest/src/toml/deprecation.rs
  crates/pixi_manifest/src/toml/feature.rs
  crates/pixi_manifest/src/toml/manifest.rs
  crates/pixi_manifest/src/toml/mod.rs
  crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__task__test__depends_on_deprecation.snap
  crates/pixi_manifest/src/toml/target.rs
  crates/pixi_manifest/src/toml/task.rs
  crates/pixi_manifest/src/toml/warning.rs
  crates/pixi_manifest/src/utils/test_utils.rs
  src/main.rs
Labels: UX

#2894 ci: bump timeout for macOS x86_64
  .github/workflows/ci.yml
Labels: test:extra_slow

#2915 docs: fix tests and add win-64 to pytorch
  docs/features/pytorch.md
  docs/source_files/pixi_tomls/pytorch-conda-forge-envs.toml
  docs/source_files/pixi_tomls/pytorch-conda-forge.toml
  tests/integration_python/test_docs_examples.py
Labels: test:extra_slow

#2937 fix: add jemalloc env var page setting to release build
  .github/workflows/release.yml
Labels: installation

#2949 docs: add multi env tutorial
  docs/source_files/pixi_tomls/multi-environment-py-envs.toml
  docs/source_files/pixi_tomls/multi-environment-simple.toml
  docs/tutorials/multi_environment.md
  mkdocs.yml
Labels: :book: documentation

#2960 fix: use same git code for pypi
  Cargo.lock
  crates/pixi_build_type_conversions/src/project_model.rs
  crates/pixi_git/src/git.rs
  crates/pixi_git/src/url.rs
  crates/pixi_manifest/Cargo.toml
  crates/pixi_manifest/src/manifests/manifest.rs
  crates/pixi_manifest/src/pypi/mod.rs
  crates/pixi_manifest/src/pypi/pypi_requirement.rs
  crates/pixi_manifest/src/pypi/pypi_requirement_types.rs
  crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_failing.snap
  crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_succeeding.snap
  crates/pixi_record/src/pinned_source.rs
  crates/pixi_spec/src/git.rs
  crates/pixi_spec/src/lib.rs
  crates/pixi_spec/src/toml.rs
  crates/pixi_uv_conversions/Cargo.toml
  crates/pixi_uv_conversions/src/conversions.rs
  crates/pixi_uv_conversions/src/requirements.rs
  examples/detectron2-from-source/pixi.lock
  examples/pypi-source-deps/pixi.lock
  src/build/mod.rs
  src/cli/cli_config.rs
  src/cli/project/export/conda_environment.rs
  src/environment.rs
  src/install_pypi/conversions.rs
  src/install_pypi/plan/mod.rs
  src/install_pypi/plan/test/harness.rs
  src/install_pypi/plan/test/mod.rs
  src/lock_file/resolve/pypi.rs
  src/lock_file/satisfiability.rs
  tests/integration_rust/add_tests.rs
Labels: test:extra_slow

#2986 fix: update solve-groups lock file
  examples/solve-groups/pixi.lock
Labels: test:extra_slow

#2968 fix: don't check requires python in satisfiability
  crates/pixi_uv_conversions/src/conversions.rs
  src/install_pypi/mod.rs
  src/install_pypi/plan/mod.rs
  src/install_pypi/plan/test/harness.rs
  src/install_pypi/plan/test/mod.rs
  src/lock_file/satisfiability.rs
  tests/data/satisfiability/pypi-dep-requires-python-issue/pixi.lock
  tests/data/satisfiability/pypi-dep-requires-python-issue/pixi.toml
Labels: test:extra_slow

#2957 fix: initialize rayon late and use uv from tag
  Cargo.lock
  Cargo.toml
  crates/pixi_build_frontend/src/tool/installer.rs
  src/build/mod.rs
  src/cli/exec.rs
  src/environment.rs
  src/global/project/mod.rs
  src/prefix.rs
Labels: test:extra_slow

#3038 chore: update rust to 1.84
  crates/pixi_config/src/lib.rs
  crates/pixi_pty/src/unix/pty_process.rs
  crates/pypi_mapping/src/lib.rs
  pixi.lock
  pixi.toml
  rust-toolchain
  src/cli/run.rs
  src/lock_file/resolve/pypi.rs
  src/lock_file/resolve/resolver_provider.rs
  src/lock_file/update.rs
  src/task/executable_task.rs
Labels: test:extra_slow
